### ISSUE TITLE
'hello-world' of asn1scc + sqlalchemy

### ISSUE THREAD

**Issue by cannadayr** [ttsiodras/DataModellingTools#10]
Greetings!

I am attempting to get 'test.py' (https://www.thanassis.space/asn1.html) working w/ sqlalchemy.

However, I keep running into this issue:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table Message has no column named fk_msgId_iid [SQL: u'INSERT INTO "Message" ("fk_msgId_iid", fk_myflag_iid, fk_value_iid, "fk_szDescription_iid", "fk_isReady_iid") VALUES (?, ?, ?, ?, ?)'] [parameters: (1, 1, 1, 1, 1)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

I keep running into this error (lack of fk_*_iid column) under a variety of examples.
It seems to be a mismatch between sqlalchemy definitions and the generated schema.
I have attempted this with postgres as well.

I was hoping you could provide some insight. Let me know if you need more information. I attempted to sign up for the mailing list but haven't received confirmation yet.

Extremely interesting project! Thanks in advance.

**Comment by ttsiodras** [comment]
Can you share (i.e. attach here) 

- The exact grammar you are using
- the updated test script that you are trying to run?

**Comment by ttsiodras** [comment]
If you prefer it, you can also just see [how we perform the DB tests](https://github.com/ttsiodras/DataModellingTools/blob/master/tests-sqlalchemy/testSQLengines.py) which are performed on PostgreSQL and SQLite (as part of our regression checks). More specifically, you can see the saving and restoring from the DB (via PK) [here](https://github.com/ttsiodras/DataModellingTools/blob/master/tests-sqlalchemy/commonTests.py).

**Comment by cannadayr** [comment]
Thanks! Very helpful. Figured out the issue.

I was using the output of `asn2dataModel.py -toSql` to produce a schema, then loading it into my database.

What I should have been doing (as demonstrated in the example), is to have let sqlalchemy create the schema, with `Base.metadata.create_all(engine)`.
