### ISSUE TITLE
Incorrect data types in the generated <project_name>_getset.{c,h} files

### ISSUE THREAD

**Issue by lavovaLampa** [ttsiodras/DataModellingTools#14]
While testing the `asn2dataModel` generated Python files on armv7 architecture, we discovered the discrepancy between the types as defined in the `<project_name>_getset.{c, h}` files and the Python implementation (i.e. `Stubs.py`).

All integer values are converted into a `long long` value and then used to call function from `_getset.c` file. However,  enumerated (i.e. ASN `ENUMERATED`) and `CHOICE` values expect to receive an `int`.

**Comment by maxime-esa** [comment]
Sorry, I don't understand - what discrepancy is there? 
Is there a problem with the Python bindings? Can you attach a grammar to reproduce the issue?

**Comment by lavovaLampa** [comment]
Sorry for the delay.

Example ASN file.
```
TEST DEFINITIONS AUTOMATIC TAGS ::= BEGIN

T-CHIP-ID-ENUM ::= ENUMERATED
{
    eChip-1       (0),
    eChip-2       (1),
    eChip-3       (2),
    eChip-4       (3),
    eChip-5       (4),
    eChip-6       (5),
    eChip-7       (6),
    eChip-8       (7)
}

END
```

This generates following "getter"/"setter" functions in `test_getset.h`.
```
/* ENUMERATED */
int T_CHIP_ID_ENUM__Get(T_CHIP_ID_ENUM* root);

/* ENUMERATED */
void T_CHIP_ID_ENUM__Set(T_CHIP_ID_ENUM* root, int value);
```

Looking at the lines `Stubs.py:280-281`, integer values are cast into a `c_long_long`. This is causes a type mismatch when calling C get/set functions.
```
    def Set(self, value, **args):  # postfix="", reset=True
        try:
            # print Clean(self._nodeTypeName) + "_" + self._Caccessor + "_Set"+postfix
            bridgeFunc = getattr(JMP, Clean(self._nodeTypeName) + "_" + self._Caccessor + "_Set" + args.get("postfix", ""))
            if isinstance(value, float):
                ctypesValue = c_double(value)
            elif isinstance(value, (int, long)):
                ctypesValue = c_longlong(value)
            else:
                ctypesValue = value
            self._params.append(ctypesValue)
            bridgeFunc(self._ptr, *self._params)
            self._params.pop()
        except Exception as e:
            oldAP = self._accessPath
            if args.get("reset", True):
                self.Reset()
            raise AsnCoderError(
                "The access path you used (%s) or the value you tried to assign (%s) is not valid. %s" % (
                    oldAP, str(value), str(e)))
        if args.get("reset", True):
            self.Reset()
```

Same things happens for `CHOICE` values.

**Comment by maxime-esa** [comment]
You are right that this looks incorrect, however the C language applies what is called "integer promotion" to prevent runtime issues. It is an implicit type conversion that makes sure an int (32 bits) is received if it is expected. 

This is why we do not have misbehavior in this interface.

I know it is it a bit counter-intuitive (_insane_ is a more accurate word for this), but there is no bug.
You can make a simple example to reproduce and see that gcc (or g++, or clang) _does not emit any single warning_ if you send a `long long` to a function when it is expecting an `int`, and that the result is not garbage: 
```
#include <stdio.h>
long long blah (int nothing, int foo) {
    printf("%d %d\n",  nothing, foo);  // foo will display "1", it will not be overflowed
    return 32LL;
}

int main(void)
{
    long long yay = 1<<31;
    int x = blah ((long long)yay, 1LL);
    printf("result: %d\n", x);   // will print 32
}
```

Also you probably saw that the `Get` function does not have this ambiguity - it does return the right type, based on a lookup table.

If you have an issue with this code on your ARM CPU, it could be that the C enums are actually not stored as int, but as char (I remember this was the case with the cross-compiler for STM32). And in that case there may be no implicit type conversion (but then sending an int would not help either).

**Comment by lavovaLampa** [comment]
The integer promotion sounds plausible as a reason, but I don't think that it happens on the Python -> C boundary. The `Set()` function in `Stubs.py` is calling a DLL library without knowing its' argument types (https://stackoverflow.com/questions/58512405/how-can-ctypes-infer-the-types-of-integers-that-are-passed).

AFAIK, when passing integer arguments to a DLL function Python uses the default integer size for the platform. Moreover, as the argument types of the called function are not defined in Stubs.py, the Python does not know that the C function expects an `int` and so it's called with a `long long` argument type.

I think the reason why it works on x64 and aarch64 is that the ABI for `long long` and `int` is almost same (they are both passed in a single 64b register). But for armv7, the ABI is different - some ASM instruction expect 64b values to be in consecutive registers, starting at an even numbered register.

The `_set()` functions get the "root" pointer passed in R0 and expect an `int` in R1, but, as the `long long` is 64b; it is passed in registers R2,R3. Thus the `_set()` functions set a wrong value.

**Comment by maxime-esa** [comment]
I have made a fix in a new branch (`fix_Stubs_for_ARM`), can you try it on your platform and let me know if that works?

PS: the up-to-date repo for DMT is on https://gitrepos.estec.esa.int/taste/dmt, I think the mirror on Github hasn't been sync'ed for a very long time.
