### ISSUE TITLE
Fix License

### ISSUE THREAD

**Issue by maxime-esa** [ttsiodras/DataModellingTools#6]
Fix the copyright and the license in all files.
Copyright has to contain Neuropublic and ESA, and license is GPL with Runtime Exception

Thanks

**Comment by ttsiodras** [comment]
Can you be more specific about the ESA part?

The switch from Semantix to Neuropublic is clear (since the acquisition took place back in 2012).

**Comment by maxime-esa** [comment]
The file LICENSE.txt is like this, and the .py files contain similar statements:
```
   1   |  (C) Semantix Information Technologies.
   2   │ 
   3   │ Semantix Information Technologies is licensing the code of the
   4   │ Data Modelling Tools (DMT) in the following dual-license mode:
   5   │ 
   6   │ Commercial Developer License:
   7   │       The DMT Commercial Developer License is the suggested version
   8   │ to use for the development of proprietary and/or commercial software.
   9   │ This version is for developers/companies who do not want to comply
  10   │ with the terms of the GNU Lesser General Public License version 2.1.
  11   │ 
  12   │ GNU LGPL v. 2.1:
  13   │       This version of DMT is the one to use for the development of
  14   │ applications, when you are willing to comply with the terms of the-
  15   │ GNU Lesser General Public License version 2.1.
  16   │ 
  17   │ Note that in both cases, there are no charges (royalties) for the
  18   │ generated code.
  19   │ 
  20   │ To purchase a commercial developer license (covering the entire
  21   │ DMT toolchain), please contact Semantix at: dmt@semantix.gr
```

The problems are:

(1) the IPR of Neuropublic is not mentionned 
(2) dmt@semantix.gr is wrong
(3) the license itself is wrong, at it was modified a few years ago with the agreement of the prime IPR owner (Neuropublic) to become GPL with Runtime Exception (i.e not LGPL).There is no double licensing (LGPL / Commercial) anymore
(4) the Copyright ESA has to be added, since ESA also owns part of th IPR

**Comment by ttsiodras** [comment]
I am not a lawyer, so I have to be careful...

I propose that I replace these banners in the 55 files they appear with a much simpler version ("For copyright and license information please consult file LICENSE.txt at the root of this code's repository"), and you can then commit the LICENSE.txt to the exact phrasing necessary.
