### ISSUE TITLE
Absolute vs relative imports in generated Python code

### ISSUE THREAD

**Issue by mcejp** [ttsiodras/DataModellingTools#9]
We are generating a Python data model from ASN using a command similar to

```
asn2dataModel -toPython -o GENERATED_CODE MODEL.asn
```

One of the outputs is `GENERATED_CODE/MODEL_asn.py`.
It uses absolute imports for the `DV` and `Stubs` modules, e.g.

```
import DV

from Stubs import (
    myassert, Clean, DataStream, COMMON)
```
However, this precludes `GENERATED_CODE` from being used as a self-contained package; in my opinion, it would make more sense to import as
```
from . import DV

from .Stubs import (
    myassert, Clean, DataStream, COMMON)
```

What is the intended way of importing and using the `MODEL_asn` module? Are there specific reasons not to make the imports relative?

**Comment by ttsiodras** [comment]
Hi Martin.

> What is the intended way...

For a simple example use, look at [this](https://www.thanassis.space/asn1.html) - and in particular, search for "test.py" in there. You'll see a small example grammar, and how it is used from python.

As to "why", keep in mind that when DMT sprung into existence back in 2006, this kind of syntax didn't even exist. If you are thinking about "pollution" of the global namespace, consider that ASN.1 types are, for all intents and purposes, as "global" as can be in application scope: they define the types that your application expects to use in its communication with the outside world.
